; PlatformIO project configuration for Roll-a-Ball Derby — ESP8266 Sensor Client
; Board: Wemos D1 Mini (ESP8266, 4 MB flash, 80 MHz)
; https://docs.platformio.org/en/stable/boards/espressif8266/d1_mini.html

[env:d1_mini]
platform               = espressif8266
board                  = d1_mini
framework              = arduino
monitor_speed          = 115200
upload_speed           = 921600
board_build.filesystem = littlefs

lib_deps =
    gilmaimon/ArduinoWebsockets@^0.5.4
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.0.0
